server:
  port: 8080
  servlet:
    context-path: "/"

application:
  auth:
    basic:
      login: "admin"
      password: "admin"

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/tickets
    username: formating-site
    password: formating-site
    driver-class-name: org.postgresql.Driver