server:
  port: ${$PORT:80}
  servlet:
    context-path: "/"

application:
  auth:
    basic:
      login: "admin"
      password: "admin"

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DBC_DATABASE_URL:jdbc:postgresql://localhost:5432/tickets}
    username: ${JDBC_DATABASE_USERNAME:formating-site}
    password: ${JDBC_DATABASE_PASSWORD:formating-site}
    driver-class-name: org.postgresql.Driver